server:
  port: ${PORT:5000}

spring:

  main:
    allow-bean-definition-overriding: true

  application:
    name: community-iot-device

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:community-iot-device}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:1234}
    tomcat:
      max-active: 3

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql

app-config:
  secrets:
    api-secret: ${API_SECRET:YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=}